### ISSUE TITLE
Missing variable name

### ISSUE THREAD

**Issue by dmusican** [BjoernDaase/remove-alt-tab-delay#1]
This no longer installs from me on Gnome 3.36 (used to work). lg shows an error of "SyntaxError: missing variable name".

**Comment by BjoernDaase** [comment]
Hmm, I do not get how this can happen....

https://github.com/BjoernDaase/remove-alt-tab-delay/commit/eaf3d530f1f9a08ede9ee50b1614f7d10b33ab12 was the only change and it only advertises 3.38 support.
Furthermore, everything works fine for me.

**Comment by dmusican** [comment]
Found it: the problem is the first line of extension.js, where it ends in a comma. Changing that to a semicolon fixes everything. I realize that this has been there all along; perhaps a maintenance fix to Gnome made that stop working? I don't know. But if you can fix that first line (I did locally), everything works.
