### ISSUE TITLE
ERROR loading extention

### ISSUE THREAD

**Issue by log-box** [BjoernDaase/remove-alt-tab-delay#2]
JS ERROR: Extension remove-alt-tab-delay@daase.net: SyntaxError: missing variable name @ /home/user/.local/share/gnome-shell/extensions/remove-alt-tab-delay@daase.net/extension.js:3

**Comment by BjoernDaase** [comment]
Thanks, this is already fixed via https://github.com/BjoernDaase/remove-alt-tab-delay/commit/b78ac74e17bd3aae89182611cfab7855ea031dcc.
