### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by kiraleos** [BjoernDaase/remove-alt-tab-delay#3]
JS ERROR: Extension remove-alt-tab-delay@daase.net: SyntaxError: missing variable name @ /home/username/.local/share/gnome-shell/extensions/remove-alt-tab-delay@daase.net/extension.js:3

Arch, Gnome 3.36.6, X11

**Comment by BjoernDaase** [comment]
Thanks, this is already fixed via https://github.com/BjoernDaase/remove-alt-tab-delay/commit/b78ac74e17bd3aae89182611cfab7855ea031dcc.
